services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
      - "8082:8082"  # Traefik metrics
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro
      - traefik-acme:/acme
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.example.com`)"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.service=api@internal"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.example.com`)"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

  obsidian:
    image: ghcr.io/linuxserver/obsidian:latest
    container_name: obsidian
    restart: unless-stopped
    security_opt:
      - no-new-privileges:false
      - seccomp:unconfined
    shm_size: "2gb"
    volumes:
      - obsidian-config:/config
      - obsidian-vaults:/vaults
    environment:
      - PUID=0
      - PGID=0
      - TZ=UTC
      - CUSTOM_USER=${OBSIDIAN_USER}
      - PASSWORD=${OBSIDIAN_PASSWORD}
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.obsidian.rule=Host(`obsidian.example.com`)"
      - "traefik.http.routers.obsidian.tls=true"
      - "traefik.http.routers.obsidian.tls.certresolver=letsencrypt"
      - "traefik.http.services.obsidian.loadbalancer.server.port=3000"
      - "traefik.docker.network=docker-compose_traefik"

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    user: root
    volumes:
      - n8n-data:/home/node/.n8n
      - obsidian-vaults:/obsidian-vaults:ro
      - /opt/leann:/opt/leann:ro
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://${N8N_HOST}/
      - GENERIC_TIMEZONE=UTC
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - N8N_METRICS=false
      - N8N_DISABLE_PRODUCTION_MAIN_PROCESS=false
      - N8N_SECURE_COOKIE=false
      - EXPRESS_TRUST_PROXY=true
      - PATH=/opt/leann:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LEANN_API_TOKEN=${LEANN_API_TOKEN}
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`${N8N_HOST}`)"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.routers.n8n.tls.certresolver=letsencrypt"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.docker.network=docker-compose_traefik"

  n8n-mcp:
    image: node:20-alpine
    container_name: n8n-mcp
    restart: unless-stopped
    working_dir: /app
    volumes:
      - /opt/n8n-mcp:/app
    environment:
      - NODE_ENV=production
      - MCP_MODE=http
      - USE_FIXED_HTTP=true
      - PORT=3100
      - HOST=0.0.0.0
      - BASE_URL=${N8N_MCP_BASE_URL}
      - AUTH_TOKEN=${N8N_MCP_AUTH_TOKEN}
      - CORS_ORIGIN=*
      - TRUST_PROXY=1
      - N8N_API_URL=${N8N_API_URL}
      - N8N_API_KEY=${N8N_API_KEY}
      - MCP_LOG_LEVEL=info
      - NODE_DB_PATH=/app/data/nodes.db
      - REBUILD_ON_START=false
    command: sh -c "npm run build && npm run start:http:fixed"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n-mcp.rule=Host(`n8n-mcp.example.com`)"
      - "traefik.http.routers.n8n-mcp.tls=true"
      - "traefik.http.routers.n8n-mcp.tls.certresolver=letsencrypt"
      - "traefik.http.services.n8n-mcp.loadbalancer.server.port=3100"
      - "traefik.docker.network=docker-compose_traefik"

  firecrawl-mcp:
    image: node:20-alpine
    container_name: firecrawl-mcp
    restart: unless-stopped
    working_dir: /app
    volumes:
      - /opt/firecrawl-mcp-server:/app
    environment:
      - NODE_ENV=production
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - PORT=3200
      - HOST=0.0.0.0
      - CLOUD_SERVICE=true
      - FIRECRAWL_API_URL=https://api.firecrawl.dev
      - LOG_LEVEL=info
    command: sh -c "npm run start"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firecrawl-mcp.rule=Host(`firecrawl-mcp.example.com`)"
      - "traefik.http.routers.firecrawl-mcp.tls=true"
      - "traefik.http.routers.firecrawl-mcp.tls.certresolver=letsencrypt"
      - "traefik.http.services.firecrawl-mcp.loadbalancer.server.port=3200"
      - "traefik.docker.network=docker-compose_traefik"

  leann-api:
    image: node:20-alpine
    container_name: leann-api
    restart: unless-stopped
    working_dir: /app
    volumes:
      - /opt/leann-api:/app
      - obsidian-vaults:/obsidian-vaults:ro
      - /opt/leann:/opt/leann:ro
      - /root/.local/share:/root/.local/share:ro
    environment:
      - NODE_ENV=production
      - PORT=3300
    command: sh -c "npm install && npm start"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leann-api.rule=Host(`leann-api.example.com`)"
      - "traefik.http.routers.leann-api.tls=true"
      - "traefik.http.routers.leann-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.leann-api.loadbalancer.server.port=3300"
      - "traefik.docker.network=docker-compose_traefik"

networks:
  traefik:
    external: false

volumes:
  portainer-data:
  traefik-acme:
  obsidian-config:
  obsidian-vaults:
  n8n-data: